site_name: thermopot documentation
site_description: 'Documentation site for thermopot Python package'
site_author: 'NU-CEM'
docs_dir: docs/
repo_name: 'NU-CEM/thermopot'
repo_url: 'https://github.com/NU-CEM/thermopot'
nav:
    - Welcome: index.md
    - Background: background.md
    - Installation: installation.md
    - Tutorial: tutorial.md
    - API: api.md
    - Contributing: contributing.md
 
theme:
  name: 'material'
  logo: images/1FAD6_color.png
  favicon: images/1FAD6_color.png
  
plugins:
- search
- mkdocstrings
- mkdocs-jupyter
  
markdown_extensions:
  - def_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - abbr
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg      
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
